# SPDX-FileCopyrightText: 2023 DE:AD:10:C5 <https://github.com/DEAD10C5/>
#
# SPDX-License-Identifier: CC0-1.0

name: PlatformIO CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hardware_test: [test/hardware_test/hardware_test.ino]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO examples
        run: pio ci --board=<ID_1> --board=<ID_2> --board=<ID_N>
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.hardware_test }}
